// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionActivity } from "./SessionActivity";

export type AudioProcessInfo = { pid: number, 
/**
 * Executable file name, e.g. `msedge.exe`.
 */
name: string, 
/**
 * Full executable path when the process could be opened.
 */
executable: string | null, 
/**
 * Max activity across the process's audio sessions (expired excluded).
 */
state: SessionActivity, 
/**
 * Render endpoints this process has sessions on.
 */
deviceIds: Array<string>, displayName: string | null, };
