// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Capabilities = { deviceCapture: boolean, deviceLoopback: boolean, followDefaultOutput: boolean, followDefaultInput: boolean, processLoopback: boolean, processLoopbackExclude: boolean, audioProcessList: boolean, deviceEvents: boolean, mediaSessions: boolean, mediaArtwork: boolean, spectrum: boolean, pcmStream: boolean, };
