// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CaptureSource = { "type": "device", deviceId: string, } | { "type": "defaultOutput" } | { "type": "defaultInput" } | { "type": "process", pid: number, } | { "type": "systemExcludingProcess", pid: number, };
