// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CaptureStats = { framesEmitted: number, framesDropped: number, pcmChunksEmitted: number, ringOverflows: number, starvedTicks: number, restarts: number, };
