// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioFormat } from "./AudioFormat";
import type { CaptureSource } from "./CaptureSource";
import type { CaptureState } from "./CaptureState";
import type { CaptureStats } from "./CaptureStats";
import type { PcmConfig } from "./PcmConfig";
import type { SpectrumConfig } from "./SpectrumConfig";

export type CaptureInfo = { captureId: string, state: CaptureState, source: CaptureSource, deviceId: string | null, format: AudioFormat | null, spectrum: SpectrumConfig, pcm: PcmConfig, startedAtMs: number, stats: CaptureStats, };
