// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CaptureSource } from "./CaptureSource";
import type { PcmConfig } from "./PcmConfig";
import type { SpectrumConfig } from "./SpectrumConfig";

export type CaptureStartParams = { source: CaptureSource, spectrum: SpectrumConfig | null, pcm: PcmConfig | null, };
