// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioFormat } from "./AudioFormat";
import type { CaptureState } from "./CaptureState";
import type { PcmConfig } from "./PcmConfig";
import type { SpectrumConfig } from "./SpectrumConfig";

export type CaptureStartResult = { captureId: string, state: CaptureState, deviceId: string | null, format: AudioFormat, spectrum: SpectrumConfig, pcm: PcmConfig, };
