// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioFormat } from "./AudioFormat";
import type { DeviceKind } from "./DeviceKind";
import type { DeviceState } from "./DeviceState";

export type DeviceInfo = { 
/**
 * Stable OS endpoint id (WASAPI endpoint id on Windows).
 */
id: string, name: string, kind: DeviceKind, isDefault: boolean, isDefaultCommunications: boolean, state: DeviceState, 
/**
 * Shared-mode mix format; `null` unless the device is active.
 */
format: AudioFormat | null, };
