// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioFormat } from "./AudioFormat";
import type { CaptureState } from "./CaptureState";
import type { DefaultRole } from "./DefaultRole";
import type { DeviceInfo } from "./DeviceInfo";
import type { DeviceKind } from "./DeviceKind";
import type { DeviceState } from "./DeviceState";
import type { ExitReason } from "./ExitReason";
import type { MediaChangeKind } from "./MediaChangeKind";
import type { MediaSession } from "./MediaSession";
import type { PcmFormat } from "./PcmFormat";
import type { StateReason } from "./StateReason";

export type Event = { "event": "device.added", "data": { device: DeviceInfo, } } | { "event": "device.removed", "data": { deviceId: string, } } | { "event": "device.stateChanged", "data": { deviceId: string, state: DeviceState, } } | { "event": "device.defaultChanged", "data": { kind: DeviceKind, role: DefaultRole, deviceId: string | null, } } | { "event": "capture.state", "data": { captureId: string, state: CaptureState, deviceId: string | null, format: AudioFormat | null, reason: StateReason | null, } } | { "event": "capture.spectrum", "data": { captureId: string, 
/**
 * Per-capture counter; gaps mean frames were dropped under backpressure.
 */
seq: number, timestampMs: number, 
/**
 * Per-channel RMS of this tick's time-domain samples, 0..1.
 */
rms: Array<number>, 
/**
 * `bands[channel][band]`, low -> high frequency, values 0..1.
 */
bands: Array<Array<number>>, } } | { "event": "capture.pcm", "data": { captureId: string, seq: number, timestampMs: number, 
/**
 * Cumulative frame index of the first frame in this chunk.
 */
firstSampleIndex: number, sampleRate: number, channels: number, format: PcmFormat, dataBase64: string, } } | { "event": "media.sessionsChanged", "data": { sessions: Array<MediaSession>, currentSessionId: string | null, } } | { "event": "media.currentChanged", "data": { currentSessionId: string | null, session: MediaSession | null, } } | { "event": "media.sessionUpdated", "data": { session: MediaSession, changed: Array<MediaChangeKind>, } } | { "event": "sidecar.exiting", "data": { reason: ExitReason, } };
