// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Capabilities } from "./Capabilities";
import type { Limits } from "./Limits";

export type HelloResult = { name: string, version: string, protocolVersion: number, platform: string, osVersion: string, pid: number, startedAtMs: number, capabilities: Capabilities, limits: Limits, 
/**
 * Effective artwork cache directory (`--artwork-dir`), or null when
 * caching is disabled. Bare `--artwork-dir` resolves to a sidecar-managed
 * temp location reported here.
 */
artworkDir: string | null, };
