// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PcmFormat } from "./PcmFormat";

export type Limits = { maxCaptures: number, maxFps: number, maxBands: number, fftSizes: Array<number>, pcmFormats: Array<PcmFormat>, };
