// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MediaTimeline = { positionMs: number, startTimeMs: number, endTimeMs: number, minSeekMs: number, maxSeekMs: number, 
/**
 * Unix ms of the OS-side timeline update; extrapolate the live position
 * as `positionMs + playbackRate * (now - lastUpdatedAtMs)` while playing.
 */
lastUpdatedAtMs: number, };
