// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MediaSession } from "./MediaSession";

export type MediaGetSessionsResult = { sessions: Array<MediaSession>, currentSessionId: string | null, };
