// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MediaGetArtworkResult = { contentType: string, byteLength: number, 
/**
 * Present unless `writeTo` was used.
 */
dataBase64?: string, 
/**
 * Absolute path of the written file (only with `writeTo`).
 */
file?: string, 
/**
 * Content hash — identical images yield identical hashes/paths.
 */
hash?: string, };
