// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MediaGetArtworkParams = { sessionId: string, maxBytes: number, 
/**
 * When set: instead of returning base64, write the artwork into this
 * DIRECTORY as `<hash>.<ext>` (atomic, content-addressed — same scheme
 * and shared cache as `--artwork-dir`) and return `file` + `hash`.
 */
writeTo?: string, };
