// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MediaTimeline } from "./MediaTimeline";
import type { PlaybackStatus } from "./PlaybackStatus";
import type { PlaybackType } from "./PlaybackType";
import type { RepeatMode } from "./RepeatMode";

export type MediaSession = { 
/**
 * `{appId}#{n}` — stable while the underlying OS session lives.
 */
sessionId: string, 
/**
 * Source app user model id on Windows; bus name on Linux.
 */
appId: string, isCurrent: boolean, title: string, artist: string, album: string, albumArtist: string, trackNumber: number | null, genres: Array<string>, playbackType: PlaybackType, playbackStatus: PlaybackStatus, playbackRate: number | null, shuffle: boolean | null, repeat: RepeatMode | null, artworkAvailable: boolean, 
/**
 * Always null on Windows; Linux MPRIS may expose an art URL the host fetches.
 */
artworkUrl: string | null, 
/**
 * Set only when the sidecar runs with `--artwork-dir`: absolute path of
 * the cached artwork file (content-hash named, written atomically).
 */
artworkFile: string | null, 
/**
 * Content hash of the cached artwork; changes iff the image changes.
 */
artworkHash: string | null, timeline: MediaTimeline | null, };
