// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PcmFormat } from "./PcmFormat";

export type PcmConfig = { enabled: boolean, format: PcmFormat, chunkMs: number, };
