// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BandMode } from "./BandMode";
import type { ChannelMode } from "./ChannelMode";
import type { ScaleMode } from "./ScaleMode";

/**
 * Spectrum processing configuration. Every field is optional on the wire;
 * the resolved values are echoed back in the `capture.start` result.
 */
export type SpectrumConfig = { enabled: boolean, bands: number, fps: number, channels: ChannelMode, fftSize: number, minFreq: number, 
/**
 * Clamped to 0.95 * nyquist of the actual capture rate.
 */
maxFreq: number, scale: ScaleMode, dbFloor: number, bandMode: BandMode, 
/**
 * Per-frame lerp factors referenced at 30 fps (converted for other rates).
 */
attack: number, decay: number, autoGain: boolean, 
/**
 * Fixed gain used when `autoGain` is false.
 */
gain: number, };
