// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Machine-readable reason attached to `capture.state` transitions.
 */
export type StateReason = { 
/**
 * e.g. `deviceInvalidated`, `deviceRemoved`, `defaultDeviceChanged`,
 * `processExited`, `initFailed`, `panic`.
 */
code: string, message: string, };
